
FROM node:10-alpine

#ENV NODE_ENV=development
#ENV HOST 0.0.0.0
#EXPOSE 3000
#
#WORKDIR /root/frontend
#COPY package.json /root/frontend
##VOLUME f
###此为cnpm淘宝镜像
#RUN npm config set registry https://registry.npm.taobao.org
#RUN npm install


